import colorama
import os
import datetime
import time

def handle(code:str, reason:str | None = "Unspecified reason", failure:str | None = "Unknown"):
    #ONE OF THE ARGUMENTS IS CALLED FAILURE LMAOOO
    print(colorama.Back.RESET, colorama.Fore.RESET, f"UniversalCMD has encountered a serious error, pay attention to the red screen ahead!")
    time.sleep(4)
    if code == "OPTIONS_NOT_FOUND":
        for i in range(1, 100):    
            print(colorama.Back.RED)
        print(f"UniversalCMD has failed to initialise!            ")    
        print(f"                                                  ")    
        print(f"The \"options.json\" file wasn't found!           ")
        print(f"This file is required to save data across sessions")
        print(f"and record certain variables across files         ")
        print(f"(some of which are required for UniversalCMD!)    ")
        print(f"                                                  ")
        print(f"Please report this in the UniversalCMD repo!      ")
        print(f"Code: OPTIONS_NOT_FOUND                           ")
        print(f"What failed: {failure}                            ")
        print(f"                                                  ")
        print(f"Press enter to exit with return code 1.")
        input()
        os._exit(1)
    if code == "MAX_FUNC_DEPTH_NEARBY":
        for i in range(1, 100):    
            print(colorama.Back.RED)
        print(f"A near-unavoidable error has occurred! ")    
        print(f"                                                  ")    
        print(f"Python has a function limit of 1000 functions     ")
        print(f"nested within eachother, at the moment,           ")
        print(f"975 functions have been nested.                   ")
        print(f"(there's an error of 25 to account for functions not counted)")
        print(f"                                                  ")
        print(f"UniversalCMD will now exit in order to prevent    ")
        print(f"an unavoidable exception.                         ")
        print(f"                                                  ")
        print(f"Code: MAX_FUNC_DEPTH_NEARBY                       ")
        print(f"What failed: the limitations of computing         ")
        # what else was i supposed to put for the "what failed" bit?
        print(f"                                                  ")
        print(f"Press enter to forcibly exit.")
        input()
        os._exit(1)
    if code == "FEATURE_INSTALLATION_FAILURE":
        for i in range(1, 100):    
            print(colorama.Back.RED)
        print(f"A possibly fatal error has occurred! ")    
        print(f"                                                  ")    
        print(f"Installing an optional feature has failed,        ")
        print(f"in order to make the features into commands,      ")
        print(f"UniversalCMD's code must be modified, so          ")
        print(f"UniversalCMD may or may not be corrupted,         ")
        print(f"please re-download UniversalCMD from MrBmin's     ")
        print(f"GitHub profile!                                   ")
        print(f"                                                  ")
        print(f"Please report this in the UniversalCMD repo!      ")
        print(f"Code: FEATURE_INSTALLATION_FAILURE                ")
        print(f"What failed: {failure}                            ")
        print(f"                                                  ")
        print(f"Press enter to exit with return code 1.")
        input()
        os._exit(1)
    if code == "FORCE_EXIT":
        for i in range(1, 100):    
            print(colorama.Back.RED)
        print(f"An error has occurred! ")    
        print(f"                                                  ")    
        print(f"UniversalCMD has needed to forcibly exit because: ")
        print(reason)
        print(f"                                                  ")
        print(f"Please report this in the UniversalCMD repo!      ")
        print(f"Code: FORCE_EXIT                                  ")
        print(f"What failed: {failure}                            ")
        print(f"                                                  ")
        print(f"Press enter to forcibly exit.")
        input()
        os._exit(1)
    if code == "BATCH_FAIL":
        for i in range(1, 100):    
            print(colorama.Back.RED)
        print(f"An error has occurred that wasn't caught anywhere! ")    
        print(f"                                                  ")    
        print(f"The execution of the specified batch file failed! ")
        print(f"this just got added and there's already a leak AAH")
        print(f"                                                  ")
        print(f"Please report this in the UniversalCMD repo!      ")
        print(f"Code: BATCH_FAIL                                  ")
        print(f"What failed: {failure}                            ")
        print(f"                                                  ")
        print(f"Press enter to return to UniversalCMD.")
        input()
        import UniversalCMD
    if code == "FILE_NOT_FOUND":
        for i in range(1, 100):    
            print(colorama.Back.RED)
        print(f"An error has occurred that wasn't caught anywhere! ")    
        print(f"                                                  ")    
        print(f"A file used by UniversalCMD wasn't found,         ")
        print(f"UniversalCMD will not execute any further         ")
        print(f"                                                  ")
        print(f"Please report this in the UniversalCMD repo!      ")
        print(f"Code: FILE_NOT_FOUND                              ")
        print(f"What failed: {failure}                            ")
        print(f"                                                  ")
        print(f"Press enter to exit with return code 1.")
        input()
        os._exit(1)
    if code == "CTRL_C_ATTEMPTED":
        for i in range(1, 100):    
            print(colorama.Back.RED)
        print(f"An error has occurred that wasn't caught anywhere! ")    
        print(f"                                                  ")    
        print(f"You shouldn't exit UniversalCMD with Ctrl+C!      ")
        print(f"                                                  ")
        print(f"You have to use the \"exit\" command to give        ")
        print(f"UniversalCMD a chance to clean temporary files!   ")
        print(f"What failed: {failure}                            ")
        print(f"                                                  ")
        print(f"Press enter to return to UniversalCMD.")
        input()
        import UniversalCMD
    if code == "UNK_ERR":
        for i in range(1, 100):    
            print(colorama.Back.RED)
        print(f"An error has occurred that wasn't caught anywhere! ")    
        print(f"                                                  ")    
        print(f"Caught unknown error!                             ")
        print(f"Error details:                                    ")
        print(reason)
        print(f"                                                  ")
        print(f"Please report this in the UniversalCMD repo!      ")
        print(f"Code: UNK_ERR                                     ")
        print(f"What failed: {failure}                            ")
        print(f"                                                  ")
        print(f"Press enter to return to UniversalCMD.")
        input()
        import UniversalCMD
    if code == "UNK_VAR":
        #no clue why i made this a seperate error to UNK_ERR but oh well you will probably never see this apart from the invoke command
        for i in range(1, 100):    
            print(colorama.Back.RED)
        print(f"An error has occurred that wasn't caught anywhere! ")    
        print(f"                                                  ")    
        print(f"Unknown variable error                            ")
        print(f"Error details:                                    ")
        print(reason)
        print(f"                                                  ")
        print(f"Please report this in the UniversalCMD repo!      ")
        print(f"Code: UNK_VAR                                     ")
        print(f"What failed: {failure}                            ")
        print(f"                                                  ")
        print(f"Press enter to return to UniversalCMD.")
        input()
        import UniversalCMD
    if code == "TAKE_FUNC_EXITED":
        for i in range(1, 100):    
            print(colorama.Back.RED)
        print(f"An error has occurred that wasn't caught anywhere! ")    
        print(f"                                                  ")    
        print(f"The core function, \"take()\", has been           ")
        print(f"quit unexpectedly, preventing command input!         ")
        print(f"                                                  ")
        print(f"Please report this in the UniversalCMD repo!      ")
        print(f"Code: TAKE_FUNC_EXITED                            ")
        print(f"What failed: {failure}                            ")
        print(f"                                                  ")
        print(f"Also report what you were doing before this error.")
        print(f"                                                  ")
        print(f"Press enter to return to UniversalCMD.")
        print("#this error code may have happened if you ran `import UniversalCMD`, just ctrl+c or something, UniversalCMD library mode hasn't even been started yet")
        input()        
        import UniversalCMD
    print(f"UniversalCMD has crashed with an invalid error code: {code}")
    #open(f"\ucmd-crashdump.txt", "x")
    #open(f"\ucmd-crashdump.txt", "w").write(f"UniversalCMD has crashed!\n\nError code:{code}\n")
print("Initialised error handler.")